### ISSUE TITLE
Fix device information via config

### ISSUE THREAD

**Issue by ConnyOnny** [RalfJung/lilass#3]
There are displays which deliver wrong information about which resolution is preferred (e.g. my 1080p TV which calls 720p the preferred resolution). If instead of "xrandr -q" we would parse the output of "xrandr -q --verbose" we could determine the device EDID and in a config file could change the preferred resolution or could add resolutions that are (falsely) not listed in the device capability list.
We could also continue parsing of xrandr -q and sparsely parse xrandr --verbose, only to get the EDIDs.

With this data we could even create a database with manufacturer ID+manufacturer product code (Bits 8 to 11 in the EDID) => repaired modes list to automatically fix devices when somebody writes a fix. Lilass could then (if configured accordingly) try to query the database online (or use a local copy of the database) to auto-fix device resolutions.

What do you think?

**Comment by RalfJung** [comment]
I'm not sure I understand. The screen reports all its supported resolutions, but you don't like its choice of the preferred/default resolution?

I'd like to focus this on what you're trying to accomplish. From what I understand, you want your TV to use a resolution which is not the one that's "preferred". Is that correct?

I think adding some manual default-overwriting or EDID "Fix" mechanism to lilass is the wrong way to achieve that. In particular, there may well be scenarios where users want a non-default resolution not because the EDID is somehow "wrong", but for different reasons - so, "fix" would already be a misnomer.
Instead, I think something should remember which configuration is used for which screen, and should select that (semi-)automatically when the screen is plugged in again. Since I am sing KDE, KScreen is always running in background, and it remembers and restores even settings that were performed by other programs. So, as a fix I would propose we discuss whether and how lilass should obtain the same functionality and remember and (semi-)automatically apply display configurations.

I see two options, which are not exclusive:
- When lilass sees a screen the second time, the defaults in the configuration window change to what has been selected last time.
- There is some command-line argument that makes lilass silent, and automatically applies the last (or a default) configuration if an external screen is connected. Users could then pass this to lilass when it is called by x-on-resize, so that previous configurations are silently restored.

Completely independently, we could decide that the default resolution selected by lilass should always be the one with the highest resolution, rather than whatever the EDID says. Whether or not that is sensible, I'm not sure.

**Comment by ConnyOnny** [comment]
- I like the first solution: selecting the last used resolution for a screen as default. Note that this also requires us to parse `xrandr --verbose` because the plug ID alone doesn't really say it's the same screen.
- I don't like the second solution (silently restoring old settings) because my gnome does that too and it sucks: I plug in my TV and right away my laptop is dark, BUT the TV isn't ready to display anything yet because it needs to "boot up" (or whatever) and also I need to select the correct source. Not seeing anything sucks. I think with the calls with parameters we provide a good tool for automation for the people who want it exactly as they want it. We shouldn't impose any "smart choice" (by us) on the users.
- The hightest resolution as default has problems with some projectors: They sometimes provide downsampling for high resolutions (e.g. the old hacker space projector did that) and you really don't want that. It's just so they can say they are "compatible" with many resolutions.

**Comment by RalfJung** [comment]
I certainly want the second solution, because I change between external and no-external screen twice a day - and I don't want to manually configure the same screens twice a day, that's just ridiculous. But I think both behaviors can co-exist, since the silent-reapply would be a new command-line option that has to manually be executed by `x-on-resize`.

> The hightest resolution as default has problems with some projectors: They sometimes provide downsampling for high resolutions (e.g. the old hacker space projector did that) and you really don't want that. It's just so they can say they are "compatible" with many resolutions.

Okay, that's a bad idea then.

**Comment by ConnyOnny** [comment]
So let's do 1 and 2: remembering the last settings for any display ever seen. If the cmdline switch `--silently-reapply` (or something like that) is given and the configuration is known, lilass will just restore the last configuration. Without the switch the config window will open BUT the last used settings will be selected and applicable by only pressing the OK-button.
Okay?

**Comment by RalfJung** [comment]
Sounds good! I think I'll call it `--quiet`.
I'll assign this for myself now; depending on the results of some stuff I do tomorrow I may or may not reassign this to you later - if you want, that is ;-)

**Comment by ConnyOnny** [comment]
two things:
1. please assign me; I can't do it
2. I think `--quiet` is misleading because if the configuration is not known, the config window _will_ open

**Comment by RalfJung** [comment]
I can't assign to you. But I un-assigned it. Consider it assigned to you ;-)

Nope, the `--quiet` I had in mind would always be quiet. If it doesn't know the screen, it uses the default configuration.

**Comment by ConnyOnny** [comment]
What is "the default configuration" concerning relative position?

I can very well imaginge `lilass --silently-reapply` being on a hotkey or called by x-on-resize. When I encounter a new situation, it'll ask me what to do and all known situations are automatically handled correctly (as _I said_, not some default)
`lilass --quiet` would not fit that user experience. What kind of UX did you have in mind for it?

**Comment by RalfJung** [comment]
I see. I think I'd call that option something with `auto`, like `--auto-apply` or so.

The UX I had in mind is that when a new screen appears, _something_ more-or-less reasonable happens, without the user having to do anything. That's the UX that most DEs (and also Windows and Mac) provide. I think it's reasonable: If you want to _configure_ the screen, you can open LiLaSS and make your selection. But if the default works fine, just use it.

**Comment by ConnyOnny** [comment]
How about this: The option is called `--guess` and the possible values are

```
always - use saved settings if known otherwise use default device settings and a default relative position (adjustable in the config file)
known - use saved settings if the device is known, otherwise open the config dialog
never - always show the config dialog, have the best guess pre-selected
```

**Comment by RalfJung** [comment]
What about `--apply`, and possible values `yes`, `no`, `auto`? "Guessing" is kind of not the right term, is it?

**Comment by ConnyOnny** [comment]
I like the term "guessing" because that's what the program does: It guesses what configuration the user might want. The value then defines in which _situations_ the program should "just take a guess" instead of showing the GUI.
I don't like "apply" because this implies that lilass usually does not apply any settings and I don't like "auto" because is is mostly undescriptive.

**Comment by RalfJung** [comment]
LiLaSS usually does not apply any settings on its own - it opens a window, letting the user choose.

That said, I still disagree about `guess`. The user tells the program exactly what to do, there is no heuristics, AI or guessing left. The only difference between the three modus operandi is whether LiLaSS automatically hits the "Ok" button (which could just as well be labeled "Apply"), or waits for the user to do so.
Instead of `auto`, we could have `if-known`, that's more descriptive.

What about `--show={always,never,on-unknown}`? Or maybe `on-new` or something else that sounds better for the third option. `always` is not completely true either, because the wndow is never shown when only one screen is connected. However, this last issue comes up with all proposals we have on the table right now.

Man, I think we're doing the very definition of bikeshedding here ;-)

**Comment by ConnyOnny** [comment]
Naming things _is_ difficult. I don't think of this discussion as bike shedding.
How about `--show-ui={if-external-display,if-new-external-display,never}`? Where `if-external-display` means there is an external diplay attached, `if-new-external-display` means there is a yet unconfigured externel display attached and `never` means lilass will just try some auto-config.
In a future version if lilass ever is able to handle single-display setups, we can add the `always` option.

We can also have a power user variant for this flag: `--uilvl={2,1,0}`

**Comment by ConnyOnny** [comment]
I think I'll do it like this: `--show-ui={on-external-display,on-new-external-display,on-error,never}`
And I'll also create this short version for power users.
`--sui={30,20,10,0}`

**Comment by RalfJung** [comment]
I almost agree ;-) . What about `--show` for the long form, and `-s` for the short one? I mean, there's nothing else to show besides the UI, is there?

Also, I don't like random magic numbers. We should rather try to find shorter versions of the strings. For example `on-external,on-new,never`. What is `--show-ui=on-error` supposed to mean?

**Comment by ConnyOnny** [comment]
okay, let's call it `--show`
For the short forms of the strings: It's difficult because if shorter strings were meaningful the strings wouldn't be so long in the first place. I like the numbers because then you can really do this stuff without much typing if you know what you're doing.
I think `--show` and `-s` should both accept both: Names and numbers.
`on-error` means if something goes wrong (whatever) there will be an error message and `never` actually means never, under any circumstances show anything (maybe for a headless enviroment :laughing: )

**Comment by RalfJung** [comment]
I don't think we should ever be hiding error messages. For headless environments, we have the option to choose another frontend, the user can pick the CLI frontend - and if they really want, they can pipe stdout and stderr to /dev/null. Hiding error messages is a footgun.

It's not like we expect people to type these commands frequently. It's something you set up once, and be good. Powerusers can add an alias to their shell if they are lazy. Random numbers are IMHO the wrong way to go here.

Considering that we are working in the context of a display configuration tool, I don't think `external-display` is worth the additional verbosity above `external`. I mean, people will not actually just come up with these strings, they will have to consider `--help` to learn about them, where we have enough space to explain them all. So, repeating `display` doesn't really help all that much, I think. But i the end, I don't care so strongly - as I mentioned above, I don't expect people to type this frequently.

**Comment by ConnyOnny** [comment]
About the headless environments I was actually kidding: Why should you need a display configuration tool in a headless environment? But yes we have the CLI frontend anyway so IF there is a use case for that (e.g. remote configuration), it's possible.

Another question: How should we store the known external displays?
- in the config file (would rather not have a tool editing its own config file)
- in a seperate file (e.g. `~/.lilass_knowledge`)

We can also think about making a `.lilass` directory and putting config and knowledge into it.

**Comment by RalfJung** [comment]
I agree, it should be a separate file. And since that means we have two files, I think we should have a folder `~/.config/lilass/`. (This should be determined using the appropriate method to obtain the XDG config folder for a given application, rather than hard-coded.) I agree the config file should move there, but we should try to be backwards-compatible: When, on startup, the old config file exists and the new one does not, LiLaSS should move the file.

Straw-man proposal for the filenames: `config` and `screens.db`.

As far as the storage format of the screen data is concerned, I don't really care - JSON, Pickle, sqlite, whatever. (Personally I would probably go with Pickle.) Please just make sure there is a version number somewhere, so that we can make changes to the format in the future.

**Comment by ConnyOnny** [comment]
I did it. It works™. I'll have to do a minor cleanup (mainly removing debugging stuff) before creating the PR. You may already take a look at the changes (see my fork).

**Comment by RalfJung** [comment]
What's the status of this? It seems like I now need this myself, so I'd like to merge it ASAP :)

**Comment by ConnyOnny** [comment]
The status is: After testing it, I'm not so happy with it anymore. Maybe that is because it not only saves the preferred resolution of a device, but also if it was on or off. So if I turn off the external screen before disconnecting, next time I connect this will happen:
1. It will suggest leaving the external display offline
2. When I say I want it online, it won't remember the resolution I used with that display

I think we have to tackle this somehow, but I don't know how.

**Comment by RalfJung** [comment]
Okay. I will then take over, and just do something based on your branch.

**Comment by RalfJung** [comment]
I reworked your code, and merged it. Thanks a lot for your work!

I ended up doing some refactoring, most of it minor. The most significant change affects the CLI interface: The tri-state `--show` actually did not make that much sense, which was particualrily obvious because of questions like "What should the default mode be?". We have `-r`/`-e`/`-i` for that. So I replaced `--show` by `--silent`, such that e.g., `lilass -s -r mirror` will use the saved data and fall back to mirror mode, never showing a UI under normal circumstances. On the other hand, `lilass -s` will show a UI for unknown screens only.

If you'd like to discuss changes to what I merged, please open a new issue.

> After testing it, I'm not so happy with it anymore. Maybe that is because it not only saves the preferred resolution of a device, but also if it was on or off. So if I turn off the external screen before disconnecting, next time I connect this will happen:
> 1. It will suggest leaving the external display offline
> 2. When I say I want it online, it won't remember the resolution I used with that display

I see that as "works as expected". Why do you turn off the external screen before disconnecting? My plan is to just unplug the cable; `x-on-resize` will notice and call `lilass` to update the screen setup.

**Comment by RalfJung** [comment]
**Addendum:** I added a `--no-db` switch to disable use of the DB. So for your use-case of disabling a screen without letting it be disabled on next re-connect, I suggest you bind a shortcut to the "disable all external screens NOW" action `lilass -i --no-db`. The tool will then _not_ remember this selection in the DB.
